apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog-server
  template:
    metadata:
      labels:
        app: blog-server
    spec:
      containers:
        - name: blog-server
          image: arshen00r/blog-server:v1
          ports:
            - containerPort: 5001
          env:
            - name: MONGO_URI
              value: mongodb://mongo:27017/BlogApp