apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "blog-app.fullname" . }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: blog-app

  template:
    metadata:
      labels:
        app: blog-app

    spec:
      containers:
        - name: blog-app

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: 80